### ISSUE TITLE
Add license to this repository

### ISSUE THREAD

**Issue by dan-coates** [RayCrafter/ansible-raycrafter#1]
[Your ideas are intriguing to me and I wish to subscribe to your newsletter.](https://www.youtube.com/watch?v=wlMwc1c0HRQ)

No but really, the grayloginputs Ansible module is something I could use in a project, but you have no license specified, putting it in a legal gray area. Would you mind adding one?

https://help.github.com/articles/open-source-licensing/

**Comment by storax** [comment]
oh sure. I'm glad you find use for it. Give me a day and I'll add a license. Sorry that is hasn't one already. If you have any questions or find my choice of license might cause trouble for you using the code, feel free to message me.

**Comment by storax** [comment]
Added a MIT License which gives you permission to use, distribute and modify the software. I hope this resolves this issue. If you have any reason against the use of the MIT license, let me know.
